execute pathogen#infect()
" Pluigins:
"  - Pathogen(loader): https://github.com/tpope/vim-pathogen
"  - NERDTree:         https://github.com/scrooloose/nerdtree
"  - SimplyFold:       https://github.com/tmhedberg/SimpylFold
"  - vim-sensible:     https://github.com/tpope/vim-sensible 
"  - vim-javascript    https://github.com/pangloss/vim-javascript
"  - vim-jshint2       https://github.com/Shutnik/jshint2.vim.git

set secure exrc

set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

set nocompatible

set autoindent
set smartindent
set noexpandtab

"I like my tabs wide
set tabstop=8 
set shiftwidth=8 

set foldmethod=syntax

set textwidth=100
set t_Co=256
syntax on

set number
set showmatch
set comments=sl:/*,mb:\ *,elx:\ */

"Comment this line off if you're using a dark on black theme
set background=dark

source ~/.vim/cyrilic.vim
 
" save a file
nmap <F2> :w<CR>
imap <F2> <ESC>:w<CR>i

map <C-N> :NERDTreeToggle <CR>
map <C-T> :tabnew <CR>
map <C-C> :q <CR>

"Compile a basic program
autocmd Filetype cpp map <F9> <ESC>:w <bar> !g++ % -o %:r -std=c++11 && ./%:r <CR>
autocmd Filetype java map <F9> <ESC>:w <bar> !javac % && java %:r <CR>

"Use tabs of size 4 for html
autocmd Filetype html       setlocal ts=4 sts=4 sw=4
autocmd Filetype htmldjango setlocal ts=4 sts=4 sw=4

autocmd Filetype javascript map <F5> <ESC> :w <bar> :JSHint <CR> <CR>
