execute pathogen#infect()
" Pluigins:
"  - Pathogen(loader): https://github.com/tpope/vim-pathogen
"  - NERDTree:         https://github.com/scrooloose/nerdtree
"  - SimplyFold:       https://github.com/tmhedberg/SimpylFold
"  - vim-sensible:     https://github.com/tpope/vim-sensible 
"  - vim-javascript    https://github.com/pangloss/vim-javascript

set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

set nocompatible

set autoindent
set smartindent
set expandtab

set tabstop=4 
set shiftwidth=4 

set foldmethod=syntax

set textwidth=80
set t_Co=256
syntax on

set number
set showmatch
set comments=sl:/*,mb:\ *,elx:\ */

"Comment this line off if you're using a dark on black theme
set background=dark
 
" save a file
nmap <F2> :w<CR>
imap <F2> <ESC>:w<CR>i

map <C-N> :NERDTreeToggle <CR>
map <C-T> :tabnew <CR>
map <C-C> :q <CR>

map <F5> <ESC> :w <bar> !xclip -selection clipboard < % <CR>

map <F10> <ESC> :wa <bar> !make <CR>

"Compile a basic program
autocmd Filetype cpp        map <F9> <ESC>:w <bar> !g++ % -o %:r -std=c++11 -fsanitize=address -DLOCAL -Wall -Wextra -Wpedantic && ./%:r <CR>
autocmd Filetype cs         map <F9> <ESC>:w <bar> !mcs % -out:%:r.exe && mono %:r.exe <CR>
autocmd Filetype java       map <F9> <ESC>:w <bar> !javac % && java %:r <CR>
autocmd Filetype python     map <F9> <ESC>:w <bar> !python % <CR>
autocmd Filetype javascript map <F9> <ESC>:w <bar> !node % <CR>
autocmd Filetype sh         map <F9> <ESC>:w <bar> !sh % <CR>

"Use tabs of size 8 for c/c++
autocmd Filetype cpp        setlocal ts=8 sts=8 sw=8 noexpandtab
autocmd Filetype c          setlocal ts=8 sts=8 sw=8 noexpandtab


let g:airline#extensions#tabline#enabled = 1

source ~/.vim/cyrilic.vim
