#!/bin/bash

cd $(dirname $0)

# bulgarian dvorak maping from nikolavp
# https://github.com/nikolavp/configs
cat bg-dvorak-phonetic >> /usr/share/X11/xkb/symbols/bg

cp xinitrc /etc/X11/xinit/xinitrc

mkdir -p /etc/X11/xorg.conf.d/
cp xorg.conf.d/* /etc/X11/xorg.conf.d/
